version: '3'

services:
  mysqlatualiza:
    image: mysql:8.0.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: "dbmysql"
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"